name: Replace atlas PNGs

on:
  push:
    paths:
      - ".github/workflows/replace_atlas_pngs.yml"

permissions:
  contents: write

jobs:
  replace:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download normalized atlases
        shell: bash
        run: |
          set -euo pipefail
          curl -L --fail --retry 3 'https://sdmntprnortheu.oaiusercontent.com/files/00000000-e1a0-81f4-8bc4-caf4fffc7c12/raw?se=2026-09-20T16%3A40%3A59Z&sp=r&sv=2026-02-06&sr=b&scid=be69135d-4cd6-53fb-af88-ecf07d2b28d4&skoid=5bfb38a5-43fb-4c63-80a1-6ae1e97e2e16&sktid=a48cca56-e6da-484e-a814-9c849652bcb3&skt=2026-09-20T08%3A50%3A05Z&ske=2026-09-21T08%3A50%3A05Z&sks=b&skv=2026-02-06&sig=Tye/JDLaKZK%2B1bEtRyVwreEMZ2oSnjpup1J53gVhY2I%3D' -o assets/atlas/fish/fish_atlas.png
          curl -L --fail --retry 3 'https://sdmntprnortheu.oaiusercontent.com/files/00000000-0760-81f4-891b-512826545bcf/raw?se=2026-09-20T16%3A41%3A01Z&sp=r&sv=2026-02-06&sr=b&scid=3939e2da-a6ff-5ba1-b56e-d90e270f3655&skoid=5bfb38a5-43fb-4c63-80a1-6ae1e97e2e16&sktid=a48cca56-e6da-484e-a814-9c849652bcb3&skt=2026-09-20T08%3A49%3A28Z&ske=2026-09-21T08%3A49%3A28Z&sks=b&skv=2026-02-06&sig=Cyg6CZkYrzJIkjZ8U3TdvEkjypshPyj9IGqd8wSS5l0%3D' -o assets/atlas/specials/specials_atlas.png
      - name: Commit
        shell: bash
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add assets/atlas/fish/fish_atlas.png assets/atlas/specials/specials_atlas.png
          git commit -m "Normalize atlas frame alignment" || exit 0
          git push
